### ISSUE TITLE
Forward / Reply in inbox on strict mode - Redirect to todo - not Inbox

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1025]
<img width="1169" alt="Screenshot 2022-09-22 at 08 12 07" src="https://user-images.githubusercontent.com/41041655/192535349-fbcef665-4d90-4db8-bb74-43c74913459b.png">

**Comment by ibkay998** [comment]
I would like to try this pls assign this to me

**Comment by sgnilreutr** [comment]
@ibkay998 Sure!
