### ISSUE TITLE
Handle if unsubscribe link is mailto

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1027]
If the unsubscribe link is actually a mailto link, check for this - and reroute it to open Juno and the composer active.

The codebase already has a way of hooking into mailto links, base it of that.

**Comment by ibkay998** [comment]
pls do assign this to me

**Comment by sgnilreutr** [comment]
@ibkay998 There you go - contact me here on via Discord https://discord.gg/peRDGMn9xa - if you have any questions.
