### ISSUE TITLE
BUG: Pressing enter does nothing

### ISSUE THREAD

**Issue by Dun-sin** [Elysium-Labs-EU/juno-core#1028]
The website says `press enter to start` but when you do that nothing happens, I'm using Firefox as my browser and didn't test it on others

![image](https://user-images.githubusercontent.com/78784850/193102583-ab412d8a-730b-4565-b205-29ea3963fadc.png)

**Comment by sgnilreutr** [comment]
@Dun-sin What does your console say? And what are you running here, local or on cloud? Please eloborate.

**Comment by Dun-sin** [comment]
Cloud, and I didn't check my console

**Comment by sgnilreutr** [comment]
@Dun-sin Please be complete with your information so I can help you. I am looking forward to your response.

**Comment by Dun-sin** [comment]
> @Dun-sin Please be complete with your information so I can help you. I am looking forward to your response.

there are no errors in the console

**Comment by sgnilreutr** [comment]
@Dun-sin ok,  and what are you running here, local or on cloud? What is the setup basically? Since the button for Google should become black, you are seeing the inactive state.

**Comment by Dun-sin** [comment]
I thought I said I was running on cloud earlier, I guess you didn't see it.

**Comment by sgnilreutr** [comment]
> I thought I said I was running on cloud earlier, I guess you didn't see it.

Ah yes, now I see it. Ok, so you are trying to access https://juno-core-dev.herokuapp.com/login as a regular user? If so, you have to request the beta access via the button below the login modal.

**Comment by Dun-sin** [comment]
> 

Fair, will close this issue then

**Comment by sgnilreutr** [comment]
@Dun-sin I am not sure what your intentions were, but if you want to develop - you can setup a local environment and connect to the cloud backend (by having me adding you to the Google test users) or by setting up a local backend as well.
