### ISSUE TITLE
Allow attachments to be previewed

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1032]
Use the icon: QiEye (in the codebase)
![Screenshot 2022-09-30 at 06 51 29](https://user-images.githubusercontent.com/41041655/193192797-d9364e6d-c2c3-43aa-9d47-f20eeea685d1.png)

The flow:
1. Press the eye icon
2. Platform will fetch the attachment (code for this already exists on download function)
3. Whilst downloading, display a loading icon
4. When process is successful, open the fetched file in a preview window (pop up like)
5. When process fails, use: "dispatch(setServiceUnavailable('Cannot preview the file'))" this will send a notice to the user.

**Comment by rksingh2001** [comment]
@sgnilreutr I would like to take up this issue

**Comment by sgnilreutr** [comment]
@rksingh2001 Good luck - for any questions hit me up on Discord's Elysium Labs community. #juno-support

**Comment by rksingh2001** [comment]
https://github.com/Elysium-Labs-EU/juno-core/pull/1081
