### ISSUE TITLE
Enhance contact card

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1039]
1. Add an option to trigger a search based on the user. This will require a rework of the search, possibly tap into a dispatch function to also sent optional query parameters. Which it will set as the current 'q' (inputfield). The search should be able to work with https://support.google.com/mail/answer/7190
2. Make the email link clickable to open the composer, this will use the `createComposeViaURL` function.

**Comment by anvikshaaa24** [comment]
@sgnilreutr can you please assign this to me ?

**Comment by sgnilreutr** [comment]
@anvikshaaa24 Hey! thanks for you interest, but I have already verbally assigned this ticket to @astro3012 

Feel free to pick another one!

**Comment by astro3012** [comment]
@sgnilreutr I'll be starting on this one soon, please assign it to me.
