### ISSUE TITLE
Apply styling to autograph in emailbody

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1042]
<img width="336" alt="Screenshot 2022-10-05 at 16 24 10" src="https://user-images.githubusercontent.com/41041655/194084910-ea80dcd8-240c-4577-8df5-5837929d279f.png">
Give it the color: gray-300

Also check for: gmail_signature, so - ideally check for anything with the className of "*signature*"

**Comment by kala2** [comment]
Hey can i take this one please?

**Comment by sgnilreutr** [comment]
@kala2 Sure, assigned to to you.

**Comment by sgnilreutr** [comment]
@kala2 The PR doesn't match the expected result from the ticket. Please review.

**Comment by ibkay998** [comment]
hello would like this to be assigned to me thanks.

**Comment by sgnilreutr** [comment]
You have been assigned
