### ISSUE TITLE
Add delete option in command palette + overview (based on preferred options)

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#1138]
![Screenshot 2023-01-08 at 17 23 12 1](https://user-images.githubusercontent.com/41041655/211207668-0a0c8365-dbb9-4732-9bb2-55f6ab0ffaa7.png)

**Comment by fayazpn** [comment]
Hello, can you assign this to me ?

**Comment by sgnilreutr** [comment]
@Fayaz-B Of course, it is assigned to you now. If you have any questions, contact me on Discord.
