### ISSUE TITLE
Reply to emails screen

### ISSUE THREAD

**Issue by jonathan-baernthaler** [Elysium-Labs-EU/juno-core#1140]
enhance the user experience for replying to emails. Currently the input field for text is aligned on the right of the email, the user is replying to. On certain screen sizes this results in a small input field. 

![image](https://user-images.githubusercontent.com/47054977/211560431-95991d72-b626-445f-8631-e1bf6c28afe3.png)

I would propose increasing the size of the input field to 50% of the vw. and aligning them below each other for smaller screen sizes

**Comment by jonathan-baernthaler** [comment]
<img width="659" alt="Screenshot 2023-01-10 at 14 22 11" src="https://user-images.githubusercontent.com/47054977/211562985-84cdf21f-70a9-4ed9-96d9-c27e1299961e.png">

something like this might work well for tablets and small screens.

**Comment by jonathan-baernthaler** [comment]
<img width="831" alt="Screenshot 2023-01-10 at 14 26 05" src="https://user-images.githubusercontent.com/47054977/211563650-f5550c5d-5fe3-4713-9378-e5d1518fc909.png">

something like this might work well on tablets and smaller screen sizes

**Comment by sgnilreutr** [comment]
@jonathan-baernthaler I like your suggestions.

I feel that the tablet experience can be optimised further. So the user can easily navigate between the thread and composer.

The most fancy and advanced example I can think of, is what if the page is scrolling, and when the composer is almost completely out of screen, it turns into a 'button' on top of the thread - when tabbed the composer scrolls back into focus.

Feel free to suggest simpler implementations.

**Comment by jonathan-baernthaler** [comment]
@sgnilreutr I like the idea. And I think it's fairly simple to do that. 
Do you have any guidance on how what the button should look like?

**Comment by sgnilreutr** [comment]
@jonathan-baernthaler I would suggest that it could give some info on the selected recipients and/or part of the body text. Although this might resemble a thread item a bit too much.
