### ISSUE TITLE
[Bug]: UI in sorting inbox shakes on moving to next

### ISSUE THREAD

**Issue by fayazpn** [Elysium-Labs-EU/juno-core#1215]
### Description

When I go to *sort inbox* page, on clicking **next** or **skip**, for a brief moment while fetching for data, the UI seems to have a bit shaky action.

### To Reproduce

1. Go to sort inbox page
2. Click on skip/ add to-do
4. See the U.I having a shaky action

### Anything else?

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Elysium-Labs-EU/juno-core/blob/dev/CODE_OF_CONDUCT.md)

**Comment by rksingh2001** [comment]
Which browser did you use @fayazpn ?

**Comment by sgnilreutr** [comment]
@rksingh2001 I have found the issue for this and will be part of a big rework on a local branch I have.

**Comment by sgnilreutr** [comment]
Taken care of in the latest merge.
