### ISSUE TITLE
Enhance - Counter on emailDetail when sorting or focusing - listen to new details

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#444]
When there are new emails being fetched during the sorting or focusing, this should adjust the total amount of email on the counter.

If sorting is started with batch of 20, counter will say 20.
If during sorting another batch of 20 is loaded on the background, the counter should say 40.

**Comment by Abhishek-90** [comment]
Hi @sgnilreutr, I would like to work on this issue. Can you guide how to recreate the issue and the concern file paths?

**Comment by sgnilreutr** [comment]
Hey @Abhishek-90 Sure! Please take some time to understand how everything is connected. It seems like a lot of files, but it just split a lot.

You will need to look into these files:

1. https://github.com/Elysium-Labs-EU/juno-core/blob/main/src/components/EmailDetail/EmailDetail.tsx
2. https://github.com/Elysium-Labs-EU/juno-core/blob/main/src/components/EmailDetail/EmailDetailHeader.tsx
3. https://github.com/Elysium-Labs-EU/juno-core/blob/main/src/components/EmailDetail/EmailPosition/EmailPosition.tsx
4. https://github.com/Elysium-Labs-EU/juno-core/blob/main/src/components/EmailDetail/DetailNavigation/DetailNavigationContainer.tsx
5. https://github.com/Elysium-Labs-EU/juno-core/blob/main/src/components/EmailDetail/DetailNavigation/DetailNavigationView.tsx

On file EmailDetail you will find logic that could refetch the email list if the user refreshes, see L115-123. The loading is done via the function on L79 - this is a dispatch. The codebase uses this loading mechanism everywhere.

On file EmailDetailHeader we receive the emailList from EmailDetail. Since we are either 'isSorting' or 'isFocused' check out that part of the render.

The EmailPosition uses the emailList from EmailDetail(Header) to render the active position.

Files 4 and 5 are there for showing how I currently am fetching additional emails whenever the user is browsing email details when NOT 'isSorting' or 'isFocused'. It will trigger a silentLoading dispatch of the similar loading function as on EmailDetail L79.
----

I hope this sets you in the right direction.
