### ISSUE TITLE
Allow download of files on Electron app

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#518]

**Comment by rksingh2001** [comment]
@sgnilreutr I will like to take up this task, can you please give me a little more explaination?

**Comment by sgnilreutr** [comment]
@rksingh2001 Hi, yes - the issue is that when you have an attachment on your email -you can download this via the browser by clicking the download button for that file. This functionality doesn't fully trigger on electron.

See this article for inspiration - https://chiragagrawal65.medium.com/how-to-download-any-file-from-your-electron-app-to-a-custom-location-in-5-steps-c8d37cc3a774

**Comment by rksingh2001** [comment]
#567 This issue is fixed
