### ISSUE TITLE
Email more options - Marking as Todo doesn't register in one click

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#557]
<img width="1416" alt="Screenshot 2022-02-02 at 09 02 17" src="https://user-images.githubusercontent.com/41041655/152115499-b7d69585-8331-4eef-9e9c-7273d951e443.png">

Clicking that button doesn't trigger the markAsToDo action right away.

**Comment by Abhishek-90** [comment]
Hi @sgnilreutr , can I take it?

**Comment by sgnilreutr** [comment]
Cannot reproduce.
