### ISSUE TITLE
Email File attachments - Add option to select attachments + download all

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#743]

**Comment by rksingh2001** [comment]
@sgnilreutr I would like to work on this issue, can you eleaborate a little more? Select attachment as I see is not working when we compose an email? Is that the issue?

**Comment by sgnilreutr** [comment]
@rksingh2001 
![Screenshot 2022-04-15 at 11 11 30](https://user-images.githubusercontent.com/41041655/163551882-437f773b-38be-4b94-bc4f-f38ab2b848a0.png)

Try setting up an email send to your self, with multiple replies including attachments (use Gmail interface for that at this moment). And you will see that the email shows all your attachments on the tab 'files'.
Right now you can select to download 1 attachment at a time - we would want to have a bulk option.

**Comment by rksingh2001** [comment]
Do we want to have the option to download all the attachments of the whole thread or a particular email of that thread? @sgnilreutr

**Comment by sgnilreutr** [comment]
We currently have the option to download the selected file. Want we want to add is the option to mass download.

This can be done for a thread or all the threads.
