### ISSUE TITLE
Show last update timestamp per inbox

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#823]
Show the timestamp discretely - add the timestamp as a 'title' to the header of the inbox.

use title attribute
<img width="1378" alt="Screenshot 2022-10-06 at 18 18 16" src="https://user-images.githubusercontent.com/41041655/194365757-f6c14408-e412-4e9d-8ffe-066ff46d9247.png">

You can attempt to fetch the timestamp from the emaillist redux state
<img width="361" alt="Screenshot 2022-10-06 at 18 18 38" src="https://user-images.githubusercontent.com/41041655/194365829-3ab0d291-296e-457d-bc52-fa8e288f26c9.png">

**Comment by ibkay998** [comment]
assign this to me
