### ISSUE TITLE
Build schema validation

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#895]
https://engineering.udacity.com/why-you-should-be-doing-schema-validation-in-react-projects-ce3c4b1df02f

**Comment by fazzaamiarso** [comment]
@sgnilreutr I assume that you want to build validation for API responses, right? I can work on this

**Comment by sgnilreutr** [comment]
@fazzaamiarso Yes, creating Zod types so it can be used system wide and to validate the apis. Good luck!
