### ISSUE TITLE
Allow user to control message

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#919]
<img width="368" alt="Screenshot 2022-08-15 at 07 27 52" src="https://user-images.githubusercontent.com/41041655/184581258-b8a79c59-37d2-4a65-97f6-f23b9b484849.png">

1. Add function to archive single message
2. Add function to delete single message

When the message is archived - check how GMail API returns the new thread object - add archive label to email detail view
When the message is deleted - check how GMail API returns the new thread object - and adapt front end accordingly.

**Comment by fazzaamiarso** [comment]
Hello @sgnilreutr, can I work on this issue? 🙂

**Comment by sgnilreutr** [comment]
@fazzaamiarso You sure can, if you have any questions contact me here or on https://discord.gg/peRDGMn9xa
