### ISSUE TITLE
Add contact card

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#938]
1. Show display name (if there is)
2. Show email address
3. Show avatar (letters)
4. Show option to filter on that contact

**Comment by astro3012** [comment]
@sgnilreutr I'd like to work on this. Could use some pointers on where to start and if there are any designs for this.

**Comment by sgnilreutr** [comment]
@astro3012 Sure, contact me on [Discord](https://discord.gg/peRDGMn9xa) for live assistance.

This would be the design - more or less.
<img width="284" alt="Screenshot 2022-10-02 at 12 10 22" src="https://user-images.githubusercontent.com/41041655/193448941-80275573-e575-42e7-b1ce-a28801998058.png">

**Comment by astro3012** [comment]
I'll get started right away. Is there any contribution requirement of creating a Draft PR to let you know that work is in progress? I've seen some repos having that.

**Comment by sgnilreutr** [comment]
@astro3012 You can just work on it and you will create a PR once you've decided it is complete
