### ISSUE TITLE
Emaillist - Selected email state

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#949]
<img width="1724" alt="Screenshot 2022-08-19 at 21 20 45" src="https://user-images.githubusercontent.com/41041655/185782254-625856be-188d-4e00-b2c9-e06c20cc4115.png">

**Comment by amreekminocha** [comment]
Hii.. Is there anyone working on this issue
If not, you can assign it to me

**Comment by sgnilreutr** [comment]
@amreekminocha Hey, you are more than welcome to take it on. Contact me on Discord if you have any questions. https://discord.gg/peRDGMn9xa
