### ISSUE TITLE
Enhance search view - Search query

### ISSUE THREAD

**Issue by sgnilreutr** [Elysium-Labs-EU/juno-core#967]
<img width="1112" alt="Screenshot 2022-08-29 at 07 55 51" src="https://user-images.githubusercontent.com/41041655/187132591-87b4524e-72e6-4012-9ce0-5a1e3631f100.png">

**Comment by aswinikalyan30** [comment]
Hey,  can I take this up?

**Comment by sgnilreutr** [comment]
@aswinikalyan30 I am checking if @rphilip2 is still handeling this. I will get back to you asap.

**Comment by rphilip2** [comment]
Hello, I'd like to be assigned this issue.

**Comment by sgnilreutr** [comment]
@aswinikalyan30 Since @rphilip2 was already working on it I assigned him the task. You are more than welcome to pick another issue, or contact me on https://discord.gg/peRDGMn9xa to figure out what you can/want to do.
